name: Comment on diff
on: [push, pull_request]

jobs:
  comment:
    runs-on: ubuntu-latest
    outputs:
      diff: ${{ steps.diff.outputs.diff }}
    steps:
    - uses: actions/checkout@v2
    - run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
    - id: diff
      run: echo "::set-output name=diff::$(git diff origin/master HEAD)"
    - run: echo ${{ needs.diff.outputs.diff }}
    - uses: ./
      with:
        pattern: test
